### PR TITLE
Use GitHub's API instead of Facebook's Graph API

### LINKED ISSUE #4: Example fails with HTTP status code 400 (Bad Request)
Running the example throws the following exception:
`org.springframework.web.client.HttpClientErrorException: 400 Bad Request`

The reason is that Facebook's Graph API requires an access token for these requests.

Suggestion: Use (e.g.) Github's API by changing the requests generated from
* http://graph.facebook.com/PivotalSoftware
* http://graph.facebook.com/CloudFoundry
* http://graph.facebook.com/SpringFramework

to

* https://api.github.com/users/PivotalSoftware
* https://api.github.com/users/CloudFoundry
* https://api.github.com/users/Spring-Projects

Happy to provide a pull request if desired.

### PR DESCRIPTION
**Pull request by jayho**
- change URLs, class names, variable names accordingly
- update README

Resolves #4

### CODE REVIEW

**Comment by gregturn** [comment]
Looks great! Question: have you signed the Spring Contributor License Agreement at https://support.springsource.com/spring_committer_signup?

**Comment by jayho** [comment]
Thanks! No I haven't signed yet, will do so shortly

**Comment by jayho** [comment]
I have signed the agreement

**Comment by gregturn** [comment]
Thanks!

**Comment by gregturn** [comment]
I'd hat tip you on Twitter but I can't find you.

**Comment by jayho** [comment]
It's @jayhoffs. My twitter account is a desolate wasteland though, maybe this cheers things up a little - thanks for this :)

**Pull request merged**
