### PR TITLE
Fix a typo for Spring Initializr

### PR DESCRIPTION
**Pull request by south37**
## WHY
`Spring Initalizr` seems to be a typo for `Spring Initializr`.

## WHAT
Fixed typos. Replaced `Spring Initalizr` with `Spring Initializr`.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@south37 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-async-method&pullRequestId=24)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-async-method&pullRequestId=24) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@south37 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-async-method&pullRequestId=24)!

**Comment by Buzzardo** [comment]
Thank you.

**Comment by south37** [comment]
Thanks for your kind review! 😄

**Pull request merged**
